name: Pull request

on: ['pull_request']

jobs:
  upload-report:
    runs-on: ubuntu-latest
    name: Run tests, collect coverage, upload coverage
    steps:
      - name: 'Checkout to another branch'
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Check formation
        run: npm run check
      - name: Create coverage
        run: npm run test
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
