name: Merge to main
on:
  push:
    branches:
      - main
jobs:
  codacy-coverage-report:
    secrets: inherit
    steps:
      - name: Run tests, collect coverage, upload coverage
        uses: ./.github/workflows/build.yaml
      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEPLOYMENT_8C0FF }}'
          projectId: deployment-8c0ff
          channelId: live
