name: Merge to main
on:
  push:
    branches:
      - main
jobs:
  codacy-coverage-report:
    - name: Run tests, collect coverage, upload coverage
      uses: ./.github/workflows/build.yaml
      secrets: inherit
    - name: Deploy to firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEPLOYMENT_8C0FF }}'
        channelId: live
        projectId: deployment-8c0ff
