name: Merge to main
on:
  push:
    branches:
      - main
jobs:
  test-env:
    name: Show env
    runs-on: ubuntu-latest
    environment: production
    env:
      VALIK: ${{ secrets.VALIK }}
    steps:
      - name: Call echo command
        run: echo $VALIK
  codacy-coverage-report:
    name: Run tests, collect coverage, upload coverage
    uses: ./.github/workflows/codacy-coverage-reporter.yaml
    secrets: inherit
