name: Merge to main
on: pull_request
jobs:
  build:
    name: Run tests, collect coverage, upload coverage
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  deploy:
    name: Run tests, collect coverage, upload coverage
    needs: build
    uses: ./.github/workflows/firebase-hosting-pull-request.yaml
    secrets: inherit
