name: Merge to main
on: pull_request
jobs:
  build:
    name: Run tests, collect coverage, upload coverage
    uses: ./.github/workflows/buil.yaml
    secrets: inherit
  deploy:
    name: Deploy to firebase
    needs: build
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    uses: FirebaseExtended/action-hosting-deploy@v0
    with:
      repoToken: '${{ secrets.GITHUB_TOKEN }}'
      firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEPLOYMENT_8C0FF }}'
      projectId: deployment-8c0ff
